### ISSUE TITLE
UI fails scale on full screen.

### ISSUE THREAD

**Issue by SecretiveShell** [sleevezipper/hass-workstation-service#100]
UI does not scale when the application is started and then full screened.

![image](https://user-images.githubusercontent.com/84923604/128423583-6329adae-b23f-47a0-9f8e-96855cbbda7a.png)

**Comment by SecretiveShell** [comment]
This also extends to when a new sensor is added. There is plenty of room to increase the size of the list but a scroll bar is used instead

**Comment by SecretiveShell** [comment]
I am fairly sure this could be fixed by redrawing the UI when there is an update

**Comment by SecretiveShell** [comment]
I am fairly sure this can be fixed by redrawing the UI when there is an update as it seems to return to normal when I re open the app.

**Comment by sleevezipper** [comment]
This will be fixed in the next release! @stefanroelofs made some great improvements to the UI. If you are developing, check out the develop branch.
