### ISSUE TITLE
Cannot start after smartscreen warning

### ISSUE THREAD

**Issue by fabsenet** [sleevezipper/hass-workstation-service#104]
I managed the smartscreen error message but was greeted after that with the next security warning. There is nothing I can do here except closing it. Any ideas? I am not running any fancy security software.

![grafik](https://user-images.githubusercontent.com/2065705/129478023-bfbe50ae-3cd9-416b-84ed-be836791c095.png)

**Comment by fabsenet** [comment]
Here I am again.

This anwer solved it https://superuser.com/a/1252757

You may want to link it in your readme?

thx and close at your wish :-)

**Comment by sleevezipper** [comment]
Thank you for figuring it out! I've added it to the readme (on de develop branch for now).
