### ISSUE TITLE
Feature Request - Option to pass JSON

### ISSUE THREAD

**Issue by manju-rn** [sleevezipper/hass-workstation-service#106]
It would be great to have ability to pass the custom JSON to the MQTT message for a sensor.  This would allow to tailor make sensors in HA (I am sure same on OpenHAB as well)  so that the Sensor entity created in HA can have required attributes, for example. creating a `device-class` or any Long Term stats like `state-class`, `measurement`

[HA Long Term Stats](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)

**Comment by sleevezipper** [comment]
Thanks for creating an issue! 

Interesting idea. These properties are hardcoded in the sensor code now. Should not be too difficult to make those configurable.
