### ISSUE TITLE
WMI Query example

### ISSUE THREAD

**Issue by lafferlaffer** [sleevezipper/hass-workstation-service#107]
Hi,

Thank you very much for making this. It's been working great. Even better then IoTLink. This seems to be more stable and reliable.

To the point; I opened an Issue as noted in your doc for the _WMIQuerySensor_.
I found something that might be useful to others. I searched for a while and couldn't find anything.

**Find process**
The following query will return the process name you search for - if it exists:
`Select * from Win32_Process Where Name = 'notepad.exe'`

I needed this to set up an automation to notify me when a process no longer exists on my computer.

**Comment by sleevezipper** [comment]
Thank you! I added it to the docs (in the develop branch for now).
