### ISSUE TITLE
Does not connect to MQTT Broker..

### ISSUE THREAD

**Issue by ChrisPiel70** [sleevezipper/hass-workstation-service#11]
HASS Workstation Service will not connect to broker.

1. Which port number is being used fir MQTT?
2. Can i enter a port number on "IP or Hostname" field?

I can connect to my broker with mqtt://XX.XX.XX.XX:8883 + [user] & [password]

**Comment by sleevezipper** [comment]
Hi @ChrisPiel70! 

The app does not support any ports except 1883 yet and it won't work when you add the port number in the "IP or Hostname" field.

**Comment by sleevezipper** [comment]
This shouldn't be too much work so I'll get on it.

**Comment by sleevezipper** [comment]
This has been implemented and will be in the next release! This will be later today or tomorrow.
