### ISSUE TITLE
App crashes when enabling Auto Start of background service

### ISSUE THREAD

**Issue by radicalmachine** [sleevezipper/hass-workstation-service#110]
UI crashes when enabling Auto Start of background service. The UI will no longer start until the app is uninstalled, the host rebooted, and re-installed. However attempting to re-enable the auto start causes the UI to crash. The cycle repeats.

**Comment by umutcelebi** [comment]
Same issue here.

**Comment by fakruger** [comment]
Did a fresh install and have the same problem/

**Comment by sleevezipper** [comment]
I made the error message more clear in the application but there's not a lot I can do about antivirus software being too eager.
