### ISSUE TITLE
WMI Query is blank

### ISSUE THREAD

**Issue by firestrife23** [sleevezipper/hass-workstation-service#117]
Here's two WMI Queries I ran in powershell is returning value but when I added those to Sensors list and it's returning blank.

C: Drive's Free Space
`Get-WmiObject -Class Win32_logicaldisk -Filter "DeviceID = 'C:'" | Select-Object @{L='FreeSpaceGB';E={"{0:N2}" -f ($_.FreeSpace /1GB)}}`

C: Drive's Capacity
`Get-WmiObject -Class Win32_logicaldisk -Filter "DeviceID = 'C:'" | Select-Object @{L="Capacity";E={"{0:N2}" -f ($_.Size/1GB)}}`

**Comment by SecretiveShell** [comment]
Can you test these commands in an external app such as WMI explorer to confirm they are valid?

**Comment by firestrife23** [comment]
WMI Explorer? I'll give it a try and let you know. I'm certain it's valid because I ran this command in PowerShell and it came back with a value.

**Comment by pKuEDhVxaGFYBTRz** [comment]
also look at https://github.com/sleevezipper/hass-workstation-service/blob/develop/documentation/WMIQuery.md#wmiquerysensor

**Comment by sleevezipper** [comment]
You can find an example for free disk space [here](https://github.com/sleevezipper/hass-workstation-service/blob/master/documentation/WMIQuery.md). Let me know if you can't get it to work!
