### ISSUE TITLE
Move uptime / idletime from relative time to absolute time

### ISSUE THREAD

**Issue by epsimatic** [sleevezipper/hass-workstation-service#12]
### Proposed changes:

- Add `LastBoot` sensor
- Add `LastActive` sensor
- Remove or disable by default `UpTime` sensor
- Remove or disable by default `IdleTime` sensor 
- If `...Time` sensors got disabled and not removed: 
  - add a warning to documentation and/or runtime warning for people trying to turn these sensors on.

### Rationale

As per [this MR to Home-Assistant](https://github.com/home-assistant/core/pull/43623) and around, we should avoid sensors that change values every second.

> In order to optimize stability and performance of HomeAssistant, sensors should use only absolute time values (store the date of the event) and not relative time values (seconds from event) so the db value doesn't change each seconds.
"uptime" integration is one leftover, so to adhere to HomeAssistant development rules, the sensor is now changed to a timestamp.

**Comment by sleevezipper** [comment]
Thanks for creating an issue! This seems like a better way to do it.

**Comment by ChrisMancini** [comment]
I have made the necessary changes to convert UpTime/IdleTime to LastBoot/LastActive. I have a local branch with my modifications. What is the proposed process to submit a PR?

**Comment by sleevezipper** [comment]
Oh that's great @ChrisMancini! Thanks a lot! 

I think the only way to submit a PR is to fork this repo, make the changes and push, and then create a PR from your repo.

**Comment by sleevezipper** [comment]
Thanks a lot for your contribution @ChrisMancini. It has been merged and will be in the next release.
