### ISSUE TITLE
speakers in use

### ISSUE THREAD

**Issue by bbrendon** [sleevezipper/hass-workstation-service#13]
currently my powershell hacks determine if I'm using the computer based on the speakers being used and the idle time away from the keyboard/mouse.

Any chance you can add speaker support?

**Comment by sleevezipper** [comment]
I'll see what I can do! What does your hack look like?

**Comment by bbrendon** [comment]
I thought it was pure powershell but it calls this exe. https://github.com/smourier/IsWindowsPlayingSound

The keyboard timeout is powershell stolen from somewhere... below.

I just run the powershell script in a loop forever upon user login and spit the data into hass. Works way better than IOTLINK. Hopefully you can succeed where they failed.

```
Add-Type @'
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace PInvoke.Win32 {

    public static class UserInput {

        [DllImport("user32.dll", SetLastError=false)]
        private static extern bool GetLastInputInfo(ref LASTINPUTINFO plii);

        [StructLayout(LayoutKind.Sequential)]
        private struct LASTINPUTINFO {
            public uint cbSize;
            public int dwTime;
        }

        public static DateTime LastInput {
            get {
                DateTime bootTime = DateTime.UtcNow.AddMilliseconds(-Environment.TickCount);
                DateTime lastInput = bootTime.AddMilliseconds(LastInputTicks);
                return lastInput;
            }
        }

        public static TimeSpan IdleTime {
            get {
                return DateTime.UtcNow.Subtract(LastInput);
            }
        }

        public static int LastInputTicks {
            get {
                LASTINPUTINFO lii = new LASTINPUTINFO();
                lii.cbSize = (uint)Marshal.SizeOf(typeof(LASTINPUTINFO));
                GetLastInputInfo(ref lii);
                return lii.dwTime;
            }
        }
    }
}
'@
```

**Comment by bbrendon** [comment]
Oh. I just remembered one maybe important bit...

I seem to recall I had to add the `IsWindowsPlayingSound` bit because  `UserInput ` didn't work for when I was playing video games. Or maybe it was because I watched movies on the computer sometimes? Hmm. Don't remember exactly but I think the prior.

**Comment by sleevezipper** [comment]
Hey @bbrendon, 

I missed your comments until now. Sorry for that! 

That .exe file you linked seems pretty cool! I might build a custom sensor where you can call a script to get a value so that it can be exposed to Home Assistant. 

An IdleTime sensor has been implemented (quite similarly to your Powershell script). Please note that this sensor will be replaced by the LastActive sensor in the next release.

**Comment by sleevezipper** [comment]
A CurrentVolume sensor has been implemented and will be in the next release.
