### ISSUE TITLE
How to downgrade version?

### ISSUE THREAD

**Issue by HepoH3** [sleevezipper/hass-workstation-service#136]
Hello!
In the new version, I ran into a problem that hardly affected other users (the problem with determining the gpu load when the miner is running - the system also does not see the gpu load, so the sensor may even work fine, but in the previous version it managed to correctly determine that the video card loaded when the miner is running). So I would like to downgrade, however I have no idea how. The installer installs the latest release, and if you download the zip folder of the previous release, it's not very clear to which folder you need to copy which file. If I understand correctly, I have to go to AppData / Local / Apps / 2.0 and somehow place the release files inside this folder.

**Comment by sleevezipper** [comment]
Hi!

Downgrading is not possible using the installer. You need Tu uninstall the application and download a .zip from the releases page. Just unpack that somewhere, start hass-workstation.exe, then start user interface.exe and disable and then re-enable autostart and you should be good!

**Comment by HepoH3** [comment]
Thank you for reply!
One more question: is there a way to check the version running? When I look at Info it says:  Service version: `1.0.0.30816`, but I can't find such version at the release page. The last one is `1.0.0.31612` and the previous one is `1.0.0.40823` (which I found kinda curious).

**Comment by sleevezipper** [comment]
Versioning is a mess right now so there's no reliable way to tell right now 😅. The latest release on GitHub is the same as the latest installer though. Hope that helps.
