### ISSUE TITLE
Cannot set mqtt credentials.

### ISSUE THREAD

**Issue by sihartley** [sleevezipper/hass-workstation-service#137]
Just did a fresh install on a windows pc (3rd one), after install and multiple restarts the mqtt credentials will not save, I enter the ip, port, user, password (non TLS), hit save nothing happens.
The mqttbroker.json file remains empty. If I enter the information into that file manually the front end / config will then not open.
following this format...
`{"Host":"192.168.1.4","Port":1883,"UseTLS":false,"Username":"your username","Password":"your password"}`
I have attempted restart, reboot, and re install....

[log20211125.txt](https://github.com/sleevezipper/hass-workstation-service/files/7607415/log20211125.txt)
[log20211125_001.txt](https://github.com/sleevezipper/hass-workstation-service/files/7607416/log20211125_001.txt)
[log20211125_002.txt](https://github.com/sleevezipper/hass-workstation-service/files/7607417/log20211125_002.txt)
[log20211125_003.txt](https://github.com/sleevezipper/hass-workstation-service/files/7607418/log20211125_003.txt)
[log20211125_004.txt](https://github.com/sleevezipper/hass-workstation-service/files/7607419/log20211125_004.txt)
[log20211126.txt](https://github.com/sleevezipper/hass-workstation-service/files/7607420/log20211126.txt)
[log20211126_001.txt](https://github.com/sleevezipper/hass-workstation-service/files/7607421/log20211126_001.txt)

Did discuss this on discord #support, was referred here.
Thanks

**Comment by pKuEDhVxaGFYBTRz** [comment]
Can you add some information about the languages installed on your PC, the keyboard layout, and your username? thanks!

**Comment by sihartley** [comment]
![Screenshot 2021-11-26 090058](https://user-images.githubusercontent.com/17423828/143616954-f9b4742f-e4d0-4025-9236-2c812a40fd33.png)
![Screenshot 2021-11-26 090147](https://user-images.githubusercontent.com/17423828/143616970-ada24ccd-2249-4420-864a-4fc8831e584f.png)

I also had an external keyboard attached, after reading some comments, I disconnected that and tried to enter the information from the laptop keyboard. Same result.

Also made sure that only one of the front ends was open as I read a comment from a user on discord regarding that...:-(

**Comment by sihartley** [comment]
@pKuEDhVxaGFYBTRz > Can you add some information about the languages installed on your PC, the keyboard layout, and your username? thanks!

What username do you want, and why?

**Comment by sihartley** [comment]
Username on discord, is @Seal. #9674
My discord username is @sihartley. I reached out on the @Seal username because it is my sons laptop that is having the issue, his discord.
Sorry if this caused confusion.

**Comment by Ov3r1d3** [comment]
@sihartley this is a visual frontend bug, when you try to save the credentials , you should not hit the save button but instead the connect button but it is hidden. 
Check https://github.com/sleevezipper/hass-workstation-service/issues/142

**Comment by sleevezipper** [comment]
The fix for the UI bug is live now! I assume this will solve you issue. Please reopen if that's not the case.
