### ISSUE TITLE
Volume up and down commands get lost after restart

### ISSUE THREAD

**Issue by mikosoft83** [sleevezipper/hass-workstation-service#138]
I configured up and down commands, I got the switches, they worked. Then I turned off my computer,, turned it on again and both MQTT switches stopped working and in the Command list on the computer they are gone. This happened on two computers already (both different hardware wise).

**Comment by sleevezipper** [comment]
Hi! Thanks for creating an issue. Can you still find the commands in the config files?

**Comment by blackice1580** [comment]
I can confirm that the commands are still in the config.json file when this happens

**Comment by Drumada** [comment]
I am running into the same issue, but when I check configured-commands.json, any of my volume up/down commands are missing. At first I thought I was inputting them incorrectly or somehow forgetting to save them as I lost them on a few different reboots. However I can easily re-create this by doing the following:

Adding a volume up/down command to HASS Workstation
Verifying it appears in Home Assistant (and is functional)
Killing hass-workstation-service.exe from task manager
Restarting Hass Workstation Service

The missing commands are still present in Home Assistant as switches with no easy way to delete them, but I assume this is an issue with HA and MQTT discovery and is not related to Hass Workstation. I only figured id mention it to help paint a complete picture of its behavior.

**Comment by dennis84de** [comment]
I'm having the same problem. The configurations for the media commands dispear when the service is started. I also tested this with killing the process and starting it again.

For now I added Key-commands for the switches I use (Mute and PlayPause).

**Comment by sleevezipper** [comment]
Hi! Thanks for creating an issue. I messed something up somewhere. It's working again and will be in the next release (which will be today).
