### ISSUE TITLE
Feature Request: Current User

### ISSUE THREAD

**Issue by grizzlyjere** [sleevezipper/hass-workstation-service#14]
You can get current user via WMI (really nice sensor type, BTW), but perhaps might be helpful to have the current user exposed as an out-of-the-box sensor?  As an alternative, maybe the docs could have a place to collect a useful list of queries?

For those wanting to use WMI, my query is:
`SELECT username FROM Win32_ComputerSystem`

**Comment by sleevezipper** [comment]
Hey thank you! And thanks for sharing. 

I think it would be nice to have many out-of-the-box sensors but the current UI is not really up for that. I'll think about it some more.

**Comment by grizzlyjere** [comment]
I wonder about automatically publishing all sensors types? Then the UI could show a grid of all included sensors with the option to enable/disable a sensor and change the update time? It could auto-generate a name and default all to enabled, so all a new user has to do is enter the MQTT broker info to get started.

Then perhaps a separate "advanced" tab where a user can manage custom WMI sensors (similar to how the current UI works with the grid/add dialog)?

**Comment by sleevezipper** [comment]
Hi @grizzlyjere,

I added your query to the readme for now with instructions so other users can add theirs too.
