### ISSUE TITLE
[VISUAL BUG] Connect buttons is hidden being just accessible using tab

### ISSUE THREAD

**Issue by feliperiffel** [sleevezipper/hass-workstation-service#142]
The connect buttons is hidden, I only found it using the tab.
Seems a visual issue only :)

![image](https://user-images.githubusercontent.com/1138973/144612798-9af51ed6-3510-4536-9e95-e0063d6a189b.png)
![image](https://user-images.githubusercontent.com/1138973/144612875-80da8120-b965-4e74-8134-2fdf5819f4b8.png)

**Comment by sleevezipper** [comment]
Oh wow, thanks for finding this! I'll work on a fix. In the meantime, just stretch the window vertically and it will show you the save button.

**Comment by sleevezipper** [comment]
This is fixed and will be in the next release!
