### ISSUE TITLE
Custom sensors

### ISSUE THREAD

**Issue by kzvdar42** [sleevezipper/hass-workstation-service#144]
Is there a way to create custom sensors?

Like if I want to track if the specific process is running?

**Comment by sleevezipper** [comment]
Not yet for processes, but there's a NamedWindowSensor that will expose if a window with a specific title is found. Would that work for you?

**Comment by kzvdar42** [comment]
Thanks for the answer!

No, as my process doesn't have a window.

I think that would be a great feature!

**Comment by kzvdar42** [comment]
Ok, I didn't see the `WMIQuerySensor`, this sensor serves my problem, as shown in your documentation: `Select * from Win32_Process Where Name = 'notepad.exe'`

Thanks for a great integration!

**Comment by sleevezipper** [comment]
Nice!
