### ISSUE TITLE
Missing TimeZone information breaks LastActive sensor (HA 2021.12.0b6)

### ISSUE THREAD

**Issue by ccorderod** [sleevezipper/hass-workstation-service#145]
Hi. Missing TimeZone information on timestamp device_class sensors (aka LastActive) breaks the sensor on HA 2021.12.0b6.

Exception in message_received when handling msg on 'homeassistant/sensor/G02ESXN04197/G02ESXN04197LastActive/state': '2021-12-10T13:49:02' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 37, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/sensor.py", line 249, in message_received self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state state = self._stringify_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state if (state := self.state) is None: File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 411, in state raise ValueError( ValueError: Invalid datetime: sensor.g02esxn04197lastactive provides state '2021-12-10 13:49:02', which is missing timezone information

**Comment by hankanman** [comment]
Can confirm, seeing the same behaviour here

**Comment by kailashrao** [comment]
Same Here,


![image](https://user-images.githubusercontent.com/66654340/145699246-40f4725f-5efb-4d1c-83ee-ac5e6fc842d6.png)

It seems the timestamp formatting has changed ^

**Comment by sleevezipper** [comment]
Thanks for creating an issue! I'm seeing this as well. I'll work on a fix.

**Comment by sleevezipper** [comment]
Fixed! I'll put out a new release later today.

**Comment by ccorderod** [comment]
@sleevezipper Thanks!. Merry Christmas :).

**Comment by varunsridharan** [comment]
Same issue.. waiting for the new release
