### ISSUE TITLE
Recent Update Issue

### ISSUE THREAD

**Issue by varunsridharan** [sleevezipper/hass-workstation-service#146]
I recently download a update and found that the sensors are not setup properly in the code
For example if i use `LastActiveSensor` it gives me the output of `LastBootSensor` 
if i use `LastBootSensor` i get the output of `SessionStateSensor`

![image](https://user-images.githubusercontent.com/1884287/145741039-c3621a5f-a2ff-4aae-977f-46587ceec80b.png)

Version : 1.0.0.30816

**Comment by sleevezipper** [comment]
Thanks for creating an issue! I'll have a look as soon as I can.

**Comment by sleevezipper** [comment]
Oh, did you try to reboot your PC? Sometimes weird things happen after updating because the old version of the service is still running. You can also try to kill the service under details in task manager and restarting it from the start menu.

**Comment by varunsridharan** [comment]
Cool. i used task manager to kill and restarted the PC and it works good now
