### ISSUE TITLE
Can't See All of the Screen

### ISSUE THREAD

**Issue by Pacers31Colts18** [sleevezipper/hass-workstation-service#148]
Version: 1.0.0.29554

I am unable to see all of the window, mainly anything past Prefix and Commands. Tried this on two different workstations:

https://imgur.com/a/56173ac

Any idea on how to get this working so I can use all of this?

**Comment by sleevezipper** [comment]
I should really add a scrollbar for the whole window. Thanks for taking the time to create an issue. I'll fix this next weekend.

**Comment by Pacers31Colts18** [comment]
Found my issue. My resolution is set to 150%. If I set it back to 100% it's fine (although then I can't see much haha).

**Comment by sleevezipper** [comment]
Ah yeah that makes sense. Although the UI should still support that I think.

**Comment by sleevezipper** [comment]
This has been fixed and will be in the next release!
