### ISSUE TITLE
GPU Load/Temperature Sensor identifies as UserNotificationState Sensors

### ISSUE THREAD

**Issue by Jay2645** [sleevezipper/hass-workstation-service#153]
Seems to have started happening with the newest update. Appears to be just a visual thing for existing sensors, but new sensors become notification sensors instead of GPU Load/Temperature sensors.

![image](https://user-images.githubusercontent.com/2058763/147428367-0cf2e8c7-93fb-4ee6-8c67-cbd1307356b0.png)

**Comment by sleevezipper** [comment]
Hi! Is this still happening? I think it may have something to do with using a newer version of the UI to configure an older version of the service. This can happen right after updating.

**Comment by sleevezipper** [comment]
I'll close this. If you're still having this problem, please let me know!

**Comment by Shiroe93** [comment]
I'm having the same problem
