### ISSUE TITLE
Automatically Reconnect

### ISSUE THREAD

**Issue by grizzlyjere** [sleevezipper/hass-workstation-service#16]
Hi!  Doesn't seem like the service continuously retries a connection to the MQTT server?  Could we have it keep retrying until the service is killed or new broker information provided?  Ran into this when restarting Home Assistant and the service sensor data wasn't updating.

Also, wonder about making Home Assistant aware of the state of the service (it's own service?) and/or introducing a way to indicate a sensor is "Unavailable" (e.g. using last will) ?  That way we know if there is a problem with communication or we can have automations ignore a sensor.

**Comment by sleevezipper** [comment]
Hey thanks for creating an issue! 

The service actually does keep trying to connect but in your case this does not seem to be working. I'll investigate what's going on later.

Reporting the service state to Home Assistant is already on my to-do list.

**Comment by sleevezipper** [comment]
I've changed the way the app reconnects to the broker and it is a lot more reliable now. Reconnects work fine now after resuming from sleep which was an issue for me before.

This will be in the next release! I'll close it for now, please reopen if you still have the issue after updating (tomorrow).
