### ISSUE TITLE
ESET Internet Security detects Hass Workstation Service as Win32/AtlasVPN.A

### ISSUE THREAD

**Issue by miGii** [sleevezipper/hass-workstation-service#167]
Newest version of Hass Workstation Service is detected as potentially unwanted software Win32/AtlasVPN.A by ESET Internet Security antivirus software. I think it is false positive, but does anyone know why this is happening?

![kuva](https://user-images.githubusercontent.com/5499752/151244901-9bf0fe26-025b-47e5-8730-a40b8fbeca21.png)

**Comment by sleevezipper** [comment]
Hi! There is a similar issue (#52) where this is being discussed. This application does use things like the Windows registry and WMI and my guess is that this makes it somehow match signatures of known security threats. You probably shouldn't take my word for it though. You can check out the source code and build the app yourself if you want to.
