### ISSUE TITLE
Feature Request: Edit Sensors

### ISSUE THREAD

**Issue by JAD92** [sleevezipper/hass-workstation-service#17]
Would it be possible to edit sensors that we've already added (currently add and delete are the options)? This would remove the need to delete and re-add them.

I've added a few, but for my requirements can change the update interval to suit, or need to rename them as per my naming standards.

**Comment by sleevezipper** [comment]
Thanks for creating an issue! Up to this point I didn't really have the need to edit a sensor but I can see why it would be useful.

**Comment by JAD92** [comment]
Thank you for the creation of this service! And thanks for considering the request. 👍

**Comment by ManCaveMedia** [comment]
I came hete for this request.
Thanks for considering!

**Comment by Chreece** [comment]
I'd say it's a little bit annoying to rebuild a sensor/command from scratch if you want to change something or you misspelled ;)

**Comment by bjakobs** [comment]
I'll +1 this :)

**Comment by haddood** [comment]
another vote

**Comment by amaisano** [comment]
+1 -- I have found that over the last couple months, some sensors have been removed and added just to change a setting, and due to either MQTT retain settings or me naming it slightly differently, I ended up with duplicate sensors/old sensors kicking around the network. Being able to edit w/o changing the name would be awesome.

**Comment by sleevezipper** [comment]
This has been implemented and will be in the next release. Many credits to @stefanroelofs for doing most of the work <3

**Comment by jrstarke** [comment]
@sleevezipper Is there an ETA on this release?

**Comment by sleevezipper** [comment]
Soon! I've been working on the deployment process today as it is really bad. I'll continue tomorrow and I expect to have a release ready.
