### ISSUE TITLE
Using the buttons instead of the switch

### ISSUE THREAD

**Issue by DrPerryCoke** [sleevezipper/hass-workstation-service#170]
Good afternoon! Is it possible to change the switch to a button for sound control?

**Comment by amaisano** [comment]
@DrPerryCoke you talking about the new `button` entity type they added to HA ("Press" momentary button aka stateless switch)? Or something else?

**Comment by DrPerryCoke** [comment]
@amaisano Yes) It is about her... since the switches have no status, this would not be a bad thing.

**Comment by amaisano** [comment]
OK cool. Yes, I too was going to make this feature request for the MQTT command switches -> buttons.

Documentation and source code here:

https://www.home-assistant.io/integrations/button/

**Comment by tankdeer** [comment]
Came looking for the same thing. Most, if not all of the commands are stateless. They should be buttons instead

**Comment by tankdeer** [comment]
Upon further research, it looks like there's a dev branch with this fixed, so whenever that gets merged we'll be good

**Comment by FaserF** [comment]
cant wait to see it in the main branch :)
