### ISSUE TITLE
Feature Request: Shutdown/Reboot command

### ISSUE THREAD

**Issue by Hypfer** [sleevezipper/hass-workstation-service#2]
To enable proper computer power controls from Home Assistant, it would be nice if this service could shut down or even reboot the computer it is running on.

Powering on the Computer is already possible with stock HA using WoL

**Comment by sleevezipper** [comment]
Thanks for creating this issue! 

To make this work we first need some infrastructure that enables us to respond to MQQT commands.

**Comment by sleevezipper** [comment]
Commands have been implemented and will be in the next release!
