### ISSUE TITLE
Feature Request: MQTT Last Will and Testiment set values to 0 or unavalible

### ISSUE THREAD

**Issue by Catsrules** [sleevezipper/hass-workstation-service#20]
I notice when I shutdown my computer home assistant shows the last value it received from the mqtt service. This is a little annoying as it could be stuck at 8% CPU or In Use forever until the service is started again. And you really don't get any feedback that the computer is off. I am still new the MQTT but I think there is a Last Will and Testiment feature of MQTT that when the MQTT server looses communications it will set these last will and testament values. 

It would be nice if we could set the values to 0 or unavailable so you can tell from Home assistant that the service/computer is shutdown or not working in someway.  

Also just wanted to say thanks for an amazing program it has been very helpful so far you did a really good job on it.

**Comment by sleevezipper** [comment]
Thanks for creating an issue! And thank you for the kind words. 

This should indeed be implemented in some way and I'll give it some thought.

**Comment by sleevezipper** [comment]
Will message has been implemented and will be in the next release. This makes sensors and commands "Unavailable" in Home Assistant.
