### ISSUE TITLE
Does this work on Windows 11? - Getting UnspecifiedError

### ISSUE THREAD

**Issue by zvaligura** [sleevezipper/hass-workstation-service#201]
I can't seem to get this to work on Windows 11. Got a new laptop and installed it just fine, but I get a UnspecifiedError at the title when entering in the hostname, etc.

It still works just perfectly on my desktop and on the old laptop. Maybe I'm missing something else?

**Comment by sleevezipper** [comment]
Yet it should work! I'm still using it on my work laptop using Windows 11. It could be a network issue, can you reach your Home Assistant UI from the new laptop?
