### ISSUE TITLE
Sensor with space in its name doesn't show up in Home Assistant

### ISSUE THREAD

**Issue by robinsmidsrod** [sleevezipper/hass-workstation-service#23]
Great piece of software!

While trying to use it, I came upon some weird behavior.

I tried to add the LastActive sensor with the name `Office PC Last Active`, and it didn't show up in Home Assistant (HA). It seems like a topic with spaces in it won't work with HA.

Could you either add an input box when generating a sensor to specify the identifier (as used to generate entity_id), or use the typical replace-space-with-underscore-and-lowercase everything method that HA uses to generate an identifier that works with HA?

**Comment by sleevezipper** [comment]
Thanks for creating an issue! And also thank you for the kind words.

I like the idea of replace-space-with-underscore-and-lowercase so I'll implement that later. The whole UI has very little input validation so there is a lot of room for improvement there.

**Comment by sleevezipper** [comment]
This has been fixed and will be in the next release.

78ed4d40d4161609c3d058ce11afd4d962345e42
