### ISSUE TITLE
Webcam/microphone sensors should be of type binary_sensor

### ISSUE THREAD

**Issue by robinsmidsrod** [sleevezipper/hass-workstation-service#25]
The microphone and webcam sensors are nice, but they should be of the type binary_sensor if you only intend to return the value true/false. Typically a binary sensor returns the value `on` or `off` to indicate its state.

Having them as binary sensors avoids the need to use automations with template code in them to determine correct value. The UI in Home Assistant (HA) would handle it automatically.

It would also be beneficial if `device_class` is specified, this way they'd get a proper icon and behavior of the boolean value in HA.

**Comment by sleevezipper** [comment]
Thanks for creating this issue!

I agree this would be better. It shouldn't be to hard to implement.

**Comment by regoras** [comment]
On a related note, I think it would also be helpful to have the powered on/off status of the whole system as a binary sensor. If the workstation service is available in any way, then on, and if unavailable then off.

**Comment by sleevezipper** [comment]
@regoras 
Agreed! I find it a bit weird that Home Assistant has no facility for that.

**Comment by regoras** [comment]
We can roughly get on/off state of the host that workstation-service is on by using the WoL integration: 

`switch:
  - platform: wake_on_lan
    name: pc_wol
    friendly_name: Desktop
    mac: macaddress
    host: hostip
    turn_off:
      service: switch.turn_on
      data:
        entity_id: switch.pc_sleep`

There's a bit of latency involved with this method, but it will detect if the host is online relatively quickly (within 10-20 seconds I think?) and then we can use the turn_off option to trigger a custom command.

**Comment by sleevezipper** [comment]
This has been implemented in 30adab9dbdcbd536ef4fe4d99d09cd444c34a59b and will be in the next release!
