### ISSUE TITLE
Command "Click for more information" button crashes UI

### ISSUE THREAD

**Issue by TomBrien** [sleevezipper/hass-workstation-service#33]
Clicking the more info button in the command pop up crashes the UI.

Environment: Window 10 20H2 with the bundled .NET 5.0 runtime

**Comment by sleevezipper** [comment]
Thanks for creating an issue!

I probably forgot something so thank you for letting me know.

**Comment by TomBrien** [comment]
No worries. It's a great service, thanks for the work :)
