### ISSUE TITLE
Bug: Fails when Password is not set, even though UI allows it

### ISSUE THREAD

**Issue by 3tcsoftware** [sleevezipper/hass-workstation-service#4]
Wen trying to run the service in background, it crashes due to a null reference exception when getting the password. The UI allows the password to be unset, and my current installation of MQTT has an unset password.

![image](https://user-images.githubusercontent.com/47141254/103486993-c4ddd580-4df9-11eb-9f86-5fcbe33129c2.png)

**Comment by sleevezipper** [comment]
Thank you for reporting!

This should indeed be possible as it is a valid use case.

**Comment by sleevezipper** [comment]
This is fixed and will be in the next release!
