### ISSUE TITLE
WebcamActiveSensor always True (Logitech C920 / Win 10 19042.804)

### ISSUE THREAD

**Issue by iankaufmann** [sleevezipper/hass-workstation-service#40]
Just fired up HASS Workstation Service for the first time hoping to utilize the webcam/microphone sensors.  

The MicrophoneActiveSensor seems to work.  It's false, then I open OBS Studio, and it goes to true.

However, the WebcamActiveSensor is true no matter what.  Windows camera settings confirms that nothing is using the camera.

Not sure what I should try.

If this worked I was going to slowly switch over from IoTLink but I'm stuck on the webcam sensor.

Thanks!

**Comment by sleevezipper** [comment]
Hi! 

The same thing happened to another user a while back and this worked for them:

A registry key may be incorrectly set. Try removing the keys under `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam` and `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam` one by one.

**Comment by iankaufmann** [comment]
Right on!  That worked!  Thanks for the quick reply, and sorry I failed to find that on my own if it's already been asked.

This is great!

**Comment by sleevezipper** [comment]
No worries. The answer could only be found on the Discord and that doesn't really make sense. Enjoy!
