### ISSUE TITLE
Sensor types not displaying correct form when adding

### ISSUE THREAD

**Issue by oywino** [sleevezipper/hass-workstation-service#49]
I just downloaded the latest version, but I couldn't find the announced service #13, and when poking around, I noticed that the correlation between the selected service and the displayed description doesn't seem to match;

![image](https://user-images.githubusercontent.com/18447119/111122000-b33d4a80-856d-11eb-9cc8-eab048571318.png)

**Comment by sleevezipper** [comment]
Ah seems I made mistake there. Thanks for reporting!

**Comment by sleevezipper** [comment]
@oywino 

By the way, the sensor you're looking for is called the CurrentVolumeSensor.

**Comment by Spiffo** [comment]
Same here:
![image](https://user-images.githubusercontent.com/3015566/111140647-e211eb80-8582-11eb-9d5f-54f79e124531.png)

**Comment by sleevezipper** [comment]
https://reddit.com/r/homeassistant/comments/m56l8t/hass_workstation_service_fourth_beta_released/gqzzse6

**Comment by hume-github** [comment]
As you flip between sensors it seems like it always displays the text from the previous one you were looking at.

**Comment by sleevezipper** [comment]
This has been fixed and will be in the next release!
