### ISSUE TITLE
Crash when setting new command

### ISSUE THREAD

**Issue by cherokee93** [sleevezipper/hass-workstation-service#51]
It crashes when setting a new command: https://gfycat.com/EachUncomfortableCuttlefish
is this a bug or I am doing something wrong?

EDIT: when settings everything, not just commands. Maybe I need a clean install? 
Any way to export/backup already existing sensors?

**Comment by sleevezipper** [comment]
Nah this should not be happening at all. Thank you for reporting, I'll have a look tonight.

**Comment by bjakobs** [comment]
Seeing same

> It crashes when setting a new command: https://gfycat.com/EachUncomfortableCuttlefish
> is this a bug or I am doing something wrong?
> 
> EDIT: when settings everything, not just commands. Maybe I need a clean install?
> Any way to export/backup already existing sensors?

Seeing the same here. rolling back to .34 and it works again.

**Comment by sleevezipper** [comment]
I'm pretty sure this is related to #49. I did a stupid thing with the sensor/command type selectors that caused this. So this will most likely be fixed in the next release.

**Comment by sleevezipper** [comment]
This should be fixed after updating. Could you please confirm when you have the time?

**Comment by cherokee93** [comment]
I confirm it is not crashing anymore, but also not saving the command? 🤔
https://gfycat.com/annualdishonestbarasingha

**Comment by sleevezipper** [comment]
It seems like the old version of the background service is still running. You can kill it using task manager or simply restart your computer.

**Comment by cherokee93** [comment]
Ok it is working perfectly now, thanks a lot 👍
