### ISSUE TITLE
Command buttons pushed out of screen

### ISSUE THREAD

**Issue by Chreece** [sleevezipper/hass-workstation-service#53]
If there are many sensors/commands in the screen the buttons from the command section are pushed out of the view and there are no scroll bars to bring them up.
![hass-workstation](https://user-images.githubusercontent.com/68458228/111184474-4e0b4880-85b1-11eb-91f5-9579c95a4019.png)

**Comment by sleevezipper** [comment]
Thanks for reporting!

**Comment by sleevezipper** [comment]
This has been fixed and will be in the next release!
