### ISSUE TITLE
Custom command switch gets stuck when hibernating windows

### ISSUE THREAD

**Issue by Syralist** [sleevezipper/hass-workstation-service#54]
I added a custom command to hibernate my machine using the cmd: "shutdown /h".

When I turn the switch ON in Home Assistant the command is executed, hibernating immediatly.

But then the switch does not turn off on its own and toggling the switch does not work. When I subscribe to the state topic I get a retained ON payload.

**Comment by sleevezipper** [comment]
Thanks for creating an issue! 

That doesn't sound right at all. I'll take a look when I can.

**Comment by hugalafutro** [comment]
I set up hass-workstation-service on 2 computers running identical Win10 versions, vps, antivir etc. Only one of them displays this behaviour, however not consistently enough for any kind of reproducibility.

As an aside, this is where a "TOGGLE" type helper in home assistant would come handy. I have almost 10 "input.boolean" helpers that I need to act as toggles, i.e. they must be always off and only do their thing when I flip them on, at which point they automatically flip off to which end I have to use either 10 automations (or a node-red flow) to monitor their state and flip them to off 0.1 sec after they flip on for any reason.

**Comment by sleevezipper** [comment]
@SecretiveShell fixed this in #122 so I'll close this and it will be included in next release!
