### ISSUE TITLE
Enhancement: Please add screen unlocked active sensor

### ISSUE THREAD

**Issue by mattstein111** [sleevezipper/hass-workstation-service#57]
This is an enhancement request. Currently using the webcam active sensor, but when the screen is locked and Windows Hello is active scanning for a known face, the webcam active sensor is triggered. If you added a sensor showing whether the screen is locked or not, I could take action based on the state of the webcam but only if the screen is also unlocked. Currently even if the screen is locked if I move the mouse the webcam springs into action for a few seconds to scan for a face, kicking off unnecessary automation, etc.

**Comment by sleevezipper** [comment]
Hi @mattstein111! Thanks for creating an issue.

I think the [SessionState](https://github.com/sleevezipper/hass-workstation-service#sessionstate) would be perfect for this.

**Comment by mattstein111** [comment]
Sure looks it! Next time I'll RTFM. Thanks, I'll close.

Amazing app, btw. Thanks.
