### ISSUE TITLE
GUI crammed

### ISSUE THREAD

**Issue by bbrendon** [sleevezipper/hass-workstation-service#59]
Lots of screen space but the Sensors field area is 2 rows and requires scrolling

![image](https://user-images.githubusercontent.com/6364477/111403977-2d172600-868b-11eb-8b0f-910f1e7bab2e.png)

**Comment by sleevezipper** [comment]
Thanks for creating an issue! The UI definitely needs some love.

**Comment by sleevezipper** [comment]
This has been fixed #60. Will be in the next release! Thanks @stefanroelofs!
