### ISSUE TITLE
Feature Request: GPU reporting

### ISSUE THREAD

**Issue by Warlord1390** [sleevezipper/hass-workstation-service#6]
Wondering if the GPU load can be added (use case is for media servers)

**Comment by sleevezipper** [comment]
This would be nice to have. I'd like this project to focus more on the user/desktop side for sensors for now so this could be a thing in the future.

**Comment by hankanman** [comment]
Second this request!

**Comment by sleevezipper** [comment]
This has been implemented and will be in the next release! 🎉
