### ISSUE TITLE
Autostart doesn't work if the start menu shortcut is moved

### ISSUE THREAD

**Issue by tboyce021** [sleevezipper/hass-workstation-service#66]
I like to avoid having unnecessary folders in the start menu (especially when they're named differently than the program, making it harder to find without searching if you don't remember the folder name) and instead move shortcuts to the top level. However, after doing this, the autostart functionality no longer works. I must keep the shortcut under the "Sleevezipper" folder in order for autostart to work.

**Comment by sleevezipper** [comment]
Thanks for creating an issue! This is the way the installer (ClickOnce) works. The actual executable is not always in the same location but the installer makes sure the shortcut is always correct. I can't think of a way around this except using a different installer. This may happen in the future but not at this time.
