### ISSUE TITLE
Sending key commands and commands messes up eventghost, possibly needs a release key instruction?

### ISSUE THREAD

**Issue by Justblair** [sleevezipper/hass-workstation-service#75]
Hi.  Just started playing with this.  But I see a problem.  

if I create MuteCommand, it is picked up in HASS and I can use it.  But it looks like it is emulating a mute button press, but not releasing the key in it's emulation.  So from then on EventGhost is behaving as if the mute key is continuing to be held down.  

This is what the eventghost log is showing.  As you can see I every press of the D key after I have used MuteCommand registers the mute as well.  If I use the physical mute button on my keyboard, eventghost goes back to normal.  Hence I think hass-workstation-service is omitting to give the key released command.

Keyboard.D
System.Mute '38.00'
Keyboard.D+VolumeMute
Keyboard.D+VolumeMute
Keyboard.D+VolumeMute

**Comment by sleevezipper** [comment]
Hi! Thanks for creating an issue. 

You're completely correct on what's happening here and this should be an easy fix.

**Comment by Justblair** [comment]
Yep I would do it myself, but I dont know C#.  I did find the solution using my friend google.  Hardest part is I can't find where hass-workstation-service has installed on my PC.  Lame I know.

**Comment by sleevezipper** [comment]
This has been fixed and will be in the next release.
