### ISSUE TITLE
The installer does not seem to handle .NET Core installation correctly.

### ISSUE THREAD

**Issue by sleevezipper** [sleevezipper/hass-workstation-service#8]
This needs more investigation, but several users reported that, even after installing the runtime, the app still won't work.

**Comment by sleevezipper** [comment]
A [kind user](https://community.home-assistant.io/u/Eeeeeediot) on the Home Assistant Forums provided this screenshot.
![afbeelding](https://user-images.githubusercontent.com/4253662/103694689-ab748f00-4f9b-11eb-9aa7-bb50a725b1cd.png)

**Comment by sleevezipper** [comment]
I figured out why this is happening. The app depends on `Microsoft.Extensions.Hosting` to start itself. To provide that, [ASP.NET Core Hosting Bundle](https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-aspnetcore-3.1.10-windows-hosting-bundle-installer) is required. 

While this is a fine workaround for most, it does need elevated access to install and I don't want that.

**Comment by Eeeeeediot** [comment]
> I figured out why this is happening. The app depends on `Microsoft.Extensions.Hosting` to start itself. To provide that, [ASP.NET Core Hosting Bundle](https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-aspnetcore-3.1.10-windows-hosting-bundle-installer) is required.

Installed this and all is working!

**Comment by sleevezipper** [comment]
This dependency won't be needed in future releases.
