### ISSUE TITLE
WMI query against different namespace

### ISSUE THREAD

**Issue by Martin781** [sleevezipper/hass-workstation-service#81]
Would it be possible to be able to select (or specify) the namespace from which we run against the WMI Queries.

**Comment by sleevezipper** [comment]
Thanks for creating an issue!

I think that should be possible. What data are you looking for?

**Comment by Prikith** [comment]
+1 for this feature, being able to run a query against ROOT/WMI would allow me to get my laptop's monitor brightness from WmiMonitorBrightness

**Comment by sleevezipper** [comment]
This has been implemented in f43ce8f9bff54fa4863b83ccd58be6ad49033053 and will be in the next release!
