### ISSUE TITLE
Is Custom Keystroke Command with multiple keys possible?

### ISSUE THREAD

**Issue by hugalafutro** [sleevezipper/hass-workstation-service#85]
Hi,

Many thanks for this app I successfully replaced join+chrome+eventghost+autoremote with just one app. I am having trouble creating custom keystroke command. I wish to create a custom "Next" command, as the media key Next doesn't do anything unless you are playing a playlist. Whereas pressing SHIFT+N forces next video on youtube (or jellyfin) regardless if in playlist or not.

I can find the hex values in https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes, SHIFT is 0x10, N is 0x4E. Is there a way to combine the values so I can type SHIFT+N? What do I need to put into the "Key" of the custom command?

Thanks for any ideas!

**Comment by lucifudge** [comment]
I haven't figured out how to do this in hass-workstation-service without a third-party tool. I'm doing it with Autohotkey until it's natively supported. Install AutoHotkey, you can make a file named "Next.ahk" somewhere like; _C:\Users\Public\Public Documents\Next.ahk_ that contains this;
`
Send, {LShift Down}n{LShift Up}
ExitApp
`
and in hass-workstation-service, add a _CustomCommand_ with the full path to the .ahk file in quotes;
`
"C:\Users\Public\Public Documents\Next.ahk"
`
I do something similar to trigger fan speed hotkeys with ArgusMonitor to spin my computer fans down automatically when I open the Plex app on my LG TV.

**Comment by hugalafutro** [comment]
Thanks for the suggestion, I was thinking there could be some roundabout way of doing it, but was hoping for something straightforward as I'm trying to reduce the number of codependent automation tools in order to reduce any potential points of failure. I've recently switched to iotlink and i personally find it easier to work with for what I need so I might as well close this I guess.
