### ISSUE TITLE
Current Volume Sensor does not return the correct volume

### ISSUE THREAD

**Issue by sgebhardt** [sleevezipper/hass-workstation-service#86]
If i set the master volume of my speakers to max, the sensor should return 100% and if I mute the sound it should return 0%. 

It seems the sensor returns the calculated peak level of the sound not the speaker volume. The value of the sensor changes if i play music also I don't change the windows sound value.

![image](https://user-images.githubusercontent.com/661509/123062057-799d9a80-d40c-11eb-93bc-b438807496e1.png)

**Comment by Chreece** [comment]
Hello @sgebhardt 
I would like to oppose that the current sensor is to check if sound is playing at the moment.
What you want is a sensor to check the current volume thus, a completely other implemantation...
I'm with you on that but I would also say that the current volume sensor isn't a thing that we need to change ;)

So to say, it's not a thing to change but a thing (Feature request) to add...

**Comment by sleevezipper** [comment]
This has been implemented as a new sensor in the meantime. Please check [the docs](https://github.com/sleevezipper/hass-workstation-service/blob/master/documentation/Sensors.md#mastervolumesensor) for more info.
