### ISSUE TITLE
Microphone active sensor

### ISSUE THREAD

**Issue by Saajt** [sleevezipper/hass-workstation-service#87]
Hi,

The microphone active sensor is always showing as on for me and is unusable. i have even disabled all microphones attached to my laptop and still the same issue.

Cheers

**Comment by sleevezipper** [comment]
Hi @Saajt, 

Sorry for taking so long to reply. Could you try the following?

A registry key may be incorrectly set. Try removing the keys under `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone` and `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone` one by one.

**Comment by sleevezipper** [comment]
I'm assuming this solved it. Let me know if it didn't!
