### ISSUE TITLE
Sensors not being detected in Home Assistant

### ISSUE THREAD

**Issue by DeeBeeKay** [sleevezipper/hass-workstation-service#95]
Hi,

  I installed this from the provided setup file, ie I'm not running the beta, though I'm happy to if it will solve this.

  Anyway, the documentation says that HA should automatically detect and configure the sensors. A day and two reboots, it still hasn't happened. Is there some special thing I need to do to encourage the sensors to get picked up? I've put my Mosquitto broker details into the app and it says All Good. But clearly something isn't.

  Pls halp, I am not a clever man.

**Comment by sleevezipper** [comment]
Hi! Thanks for creating an issue. Do you see any devices under the MQTT integration in Home Assistant?

**Comment by DeeBeeKay** [comment]
I do not. I should note that the other MQTT sensors I have are manually configured motion sensors - would this override the autodetection?

**Comment by ImaBadCoder** [comment]
are you able to connect to your mqtt server that the topics have been created?

**Comment by sleevezipper** [comment]
Sorry for taking so long to reply. Did you get it working in the meantime? If not, you could try figuring out what's going on using [MQTT Explorer](https://mqtt-explorer.com/).

**Comment by SvenWritesCode** [comment]
I got this working by changing the host from `localhost` to my actual IP in the userinterface.exe config. `localhost` connected fine, but did not work with the discovery. Upon changing it immediately worked.
