### ISSUE TITLE
Ability to specify namespace name

### ISSUE THREAD

**Issue by ImaBadCoder** [sleevezipper/hass-workstation-service#98]
I just came across your app and love it. I would like to run this on multiple computers, so it would be super beneficial if we could create a custom namespace. So instead of sensor.cpuloadsensor, something like sensor.computername_cpuloadsensor with the ability to be customized in the gui would be awesome. 

thanks!

**Comment by jbstep** [comment]
Definitely need this in my classroom.

**Comment by manju-rn** [comment]
isn't this already there?  When you create the sensor, you could provide a name of your choice, like this
![image](https://user-images.githubusercontent.com/26291847/129989104-9e3cbc61-49ef-463a-9b0a-ec1299e33538.png)

**Comment by ImaBadCoder** [comment]
manju,

I believe I enabled MQTT auto discovery, which is why I don't see this form.  If I am correct, is there a reason that you are adding them manually?

**Comment by manju-rn** [comment]
Well, the easy way is to just change the friendly name in HA to whatever you like. As long as the core entity name does not change, HA will not have any problems.  There is a feature I have requested to add custom JSON to be passed to the MQTT, this would allow for more controls - not just friendly name, but also the attributes

**Comment by jbstep** [comment]
My issue is that we image our computers often and doing this across 25-30 PC is very laborious. If we could use a generic sensor name and it could grab the host name like IOT link does, it would be perfect.

**Comment by ImaBadCoder** [comment]
agree with jbstep, would be ideal to not have to manually change anything, but have it dynamically create the sensors with the correct info.

**Comment by sleevezipper** [comment]
A prefix would indeed be nice. There's some more discussion on this in #24.

**Comment by sleevezipper** [comment]
A name prefix has been implemented and will be in the next release!
